name: Run tests

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Julia
    steps:
      - uses: actions/checkout@v4
      - name: Setup julia
        uses: julia-actions/setup-julia@v2
      - run: julia --project=test/ -e "import Pkg; Pkg.instantiate()"
      - run: julia --project=test/ test/runtests.jl
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
          flags: unittests
          name: codecov-umbrella
